# DICOM nodes configuration
nodes:
  orthanc:
    host: "localhost"
    port: 4242
    ae_title: "ORTHANC"
    description: "Default Local Orthanc DICOM server"

  radiant:
    host: "localhost"
    port: 11112
    ae_title: "RADIANT"
    description: "Radiant Viewer Dicom Node"

# Currently selected node
current_node: "orthanc"

# Current calling AE title (single value)
calling_aet: "MCPSCU"

# Directory where downloaded studies will be stored
download_directory: "/mnt/c/Users/paulo/PycharmProjects/rsna anonymizer/anonymizer/data/downloads"
